
---
- name: Setup kubectl on control node with new context
  hosts: localhost
  tasks:
  - name: Create $HOME/.kube directory if not present
    ansible.builtin.file:
      path: $HOME/.kube
      state: directory
  
  - name: cluster | kubeconfig | update kubeconfig with the right IPv4 address
    delegate_to: localhost
    become: false
    run_once: true
    ansible.builtin.replace:
      path: "/tmp/kubeconfig"
      regexp: "https://127.0.0.1:6443"
      replace: "https://{{ inventory_hostname }}:6443"

  - name: Copy k3s kube config to $HOME/.kube directory
    ansible.builtin.copy:
      src: .kube/config
      dest: $HOME/.kube
      mode: '600'