---
- name: Upgrade system
  apt:
    upgrade: dist
    # Need the force_apt_get until
    # https://github.com/ansible/ansible/issues/56832
    force_apt_get: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success

- name: packages | upgrade all packages
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  when:
    - >
      (skip_upgrade_packages is not defined or
      (skip_upgrade_packages is defined and not skip_upgrade_packages))
- name: packages | install common
  ansible.builtin.apt:
    name: "{{ packages.apt_install }}"
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success
  when:
    - packages.apt_install is defined
    - packages.apt_install is iterable
    - packages.apt_install | length > 0