---
- name: create user
  remote_user: ubuntu
  vars:
    ansible_become_pass: "Cosimoto101!"
  user:
    name: teaglebuilt
    uid: 1001

- name: sudo without password for user
  copy:
    content: 'teaglebuilt ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/teaglebuilt_nopasswd
    mode: 0440

